version: "3"

services:       # précise les différents services (images) à utiliser 
  nginx:
    build: requirements/nginx/ 
    container_name: website 
    ports:             # le port, détaillé juste en dessous
      - "443:443"  
    volumes:
      - wordpressfiles:/var/www/html      # le port, détaillé juste en dessous
    networks:
      - mynetwork
  wordpress:
    build: requirements/wordpress/
    env_file: .env
    container_name: wordpress
    volumes:
      - wordpressfiles:/var/www/html 
    networks:
      - mynetwork
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mynetwork


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/sbadr/data/mariadb
      o: bind
  wordpressfiles:
    driver: local
    driver_opts:
      type: none
      device: /home/sbadr/data/wordpress
      o: bind

networks:
  mynetwork: